Repository Raghava-Chittidi/NUSTuts-Backend, pull requests merged in 2024-07, with the labels that each got.

#53 test: added integration tests for delete, private, unprivate file
  internal/handlers/files.go
  internal/tests/files_test.go
Labels: enhancement

#55 fix: token expiry for authorised routes during testing
  internal/auth/auth.go
  internal/tests/files_test.go
  internal/tests/main_test.go
Labels: bug

#56 test: Finished integration tests for files and fixed CreateMockReques…
  internal/dataaccess/consultations.go
  internal/dataaccess/student.go
  internal/tests/files_integration_test.go
  internal/tests/files_unit_test.go
  internal/tests/main_test.go
Labels: enhancement

#57 refactor: deleted extra file
  internal/tests/files_test.go
Labels: enhancement

#58 test: Added unit tests for files
  internal/dataaccess/files.go
  internal/dataaccess/registry.go
  internal/tests/files_unit_test.go
  internal/tests/main_test.go
Labels: enhancement

#59 feat: consultations tests
  internal/dataaccess/consultations.go
  internal/database/database.go
  internal/tests/consultations_test.go
  internal/tests/files_integration_test.go
  internal/tests/main_test.go
Labels: enhancement

#66 test: initialised discussion tests and added registry cleanup
  internal/dataaccess/registry.go
  internal/tests/discussion_integration_test.go
  internal/tests/main_test.go
Labels: enhancement

#67 refactor: added better error messages
  internal/handlers/auth/studentAuth.go
  internal/handlers/auth/teachingAssistantAuth.go
Labels: enhancement

#68 fix: add missing error status codes
  internal/handlers/attendance.go
  internal/handlers/consultations.go
  internal/handlers/files.go
  internal/handlers/messages.go
  internal/handlers/websocket.go
Labels: bug

#69 test: Added unit and integrations tests for messages
  internal/dataaccess/discussion.go
  internal/dataaccess/files.go
  internal/dataaccess/message.go
  internal/database/database.go
  internal/handlers/files.go
  internal/tests/discussion_integration_test.go
  internal/tests/files_integration_test.go
  internal/tests/files_unit_test.go
  internal/tests/messages_integration_test.go
  internal/tests/messages_unit_test.go
Labels: enhancement

#70 fix: removed env load
  internal/database/database.go
Labels: bug

#71 Tests discussion
  internal/dataaccess/tutorial.go
  internal/handlers/tutorials.go
  internal/routes/routes.go
  internal/routes/tutorials.go
  internal/tests/discussion_unit_test.go
Labels: enhancement

#72 test: Added unit tests for student
  internal/tests/student_unit_test.go
Labels: enhancement

#73 test: Added unit tests for teaching assistant
  internal/dataaccess/teachingAssistant.go
  internal/tests/teaching_assistant_unit_test.go
Labels: enhancement

#74 test: Added tutorial unit tests
  internal/dataaccess/registry.go
  internal/dataaccess/tutorial.go
  internal/database/database.go
  internal/tests/student_unit_test.go
  internal/tests/teaching_assistant_unit_test.go
  internal/tests/tutorial_unit_test.go
Labels: enhancement

#75 fix: undo load env
  internal/database/database.go
Labels: enhancement

#76 test: Added registry unit tests
  internal/dataaccess/registry.go
  internal/tests/registry_unit_test.go
Labels: enhancement

#77 refactor: added comments and cleaned up some code
  internal/api/api.go
  internal/auth/auth.go
  internal/auth/role.go
  internal/auth/types.go
  internal/dataaccess/discussion.go
  internal/dataaccess/files.go
  internal/dataaccess/registry.go
  internal/dataaccess/tutorial.go
  internal/database/database.go
  internal/handlers/auth/authGeneral.go
  internal/handlers/auth/studentAuth.go
  internal/handlers/auth/teachingAssistantAuth.go
  internal/handlers/files.go
  internal/handlers/messages.go
  internal/handlers/websocket.go
  internal/middlewares/middleware.go
  internal/models/attendance.go
  internal/models/consultation.go
  internal/models/discussion.go
  internal/models/request.go
  internal/models/student.go
Labels: enhancement

#78 refactor: Added comments and cleaned up some files
  internal/dataaccess/files.go
  internal/handlers/files.go
  internal/router/router.go
  internal/routes/ping.go
  internal/routes/routes.go
  internal/tests/files_unit_test.go
  internal/util/auth.go
  internal/util/consultations.go
  internal/util/migration.go
  internal/util/utils.go
Labels: documentation

#79 feat: attendance tests
  internal/dataaccess/attendance.go
  internal/handlers/attendance.go
  internal/tests/attendance_integration_test.go
  internal/tests/attendance_unit_test.go
Labels: enhancement

#80 feat: request tests
  internal/handlers/request.go
  internal/tests/attendance_unit_test.go
  internal/tests/request_integration_test.go
  internal/tests/request_unit_test.go
Labels: enhancement

#82 docs: add comments for handlers & dataaccess
  internal/dataaccess/attendance.go
  internal/dataaccess/consultations.go
  internal/dataaccess/request.go
  internal/handlers/attendance.go
  internal/handlers/consultations.go
  internal/handlers/request.go
Labels: documentation

#83 refactor: added comments and standardized function naming
  internal/dataaccess/discussion.go
  internal/dataaccess/registry.go
  internal/dataaccess/tutorial.go
  internal/database/database.go
  internal/tests/discussion_unit_test.go
  internal/tests/registry_unit_test.go
  internal/tests/tutorial_unit_test.go
Labels: documentation

#84 fix: load env
  internal/database/database.go
Labels: bug

#85 fix: change attendance time to follow Singapore timezone
  internal/dataaccess/attendance.go
Labels: bug
